<x-layout title="Home CMS - Museum Azman">
<section class="space-y-6"><div><h2 class="museum-page-title">Home CMS</h2><p class="museum-page-subtitle">Manage the public home page. Featured cards follow published Events, Artists and Collection CMS order.</p></div>
<form method="POST" action="{{ route('admin.home.update', [], false) }}" enctype="multipart/form-data" class="space-y-6">@csrf @method('PUT')
<details class="museum-panel" open><summary class="museum-section-title cursor-pointer">Hero</summary><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="museum-field"><span>Optional Hero Title</span><input name="public_home_hero_title" value="{{ old('public_home_hero_title', $content['public_home_hero_title']) }}"></label><label class="museum-field"><span>Optional Hero Subtitle</span><input name="public_home_hero_subtitle" value="{{ old('public_home_hero_subtitle', $content['public_home_hero_subtitle']) }}"></label><label class="museum-field"><span>Replace Hero Video</span><input type="file" name="hero_video" accept="video/mp4,video/webm"></label><label class="museum-field"><span>Replace Video Poster</span><input type="file" name="hero_poster" accept="image/jpeg,image/png,image/webp"></label></div></details>
<details class="museum-panel" open><summary class="museum-section-title cursor-pointer">Featured Sections</summary><div class="mt-5 grid gap-4 md:grid-cols-2">@foreach(['events' => 'Events', 'artists' => 'Artists', 'works' => 'Selected Works'] as $key => $label)<label class="museum-field"><span>{{ $label }} Title *</span><input name="public_home_{{ $key }}_title" value="{{ old('public_home_'.$key.'_title', $content['public_home_'.$key.'_title']) }}" required></label><label class="museum-field"><span>{{ $label }} Description *</span><textarea name="public_home_{{ $key }}_description" rows="2" required>{{ old('public_home_'.$key.'_description', $content['public_home_'.$key.'_description']) }}</textarea></label>@endforeach</div>
<div class="mt-6 space-y-6 border-t border-zinc-200 pt-6">
    <div><h3 class="font-semibold">Featured Events — 3 fixed boxes</h3><p class="text-sm text-zinc-500">Choose the event displayed in each position.</p><div class="mt-3 grid gap-4 md:grid-cols-3">@foreach(range(0, 2) as $slot)<label class="museum-field"><span>Event Box {{ $slot + 1 }}</span><select name="featured_event_ids[]"><option value="">Coming Soon</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected((string) old('featured_event_ids.'.$slot, $selectedEventIds[$slot] ?? '') === (string) $event->id)>{{ $event->title }}</option>@endforeach</select></label>@endforeach</div></div>
    <div><h3 class="font-semibold">Featured Artists — 4 fixed boxes</h3><p class="text-sm text-zinc-500">Choose the artist displayed in each position.</p><div class="mt-3 grid gap-4 md:grid-cols-2 xl:grid-cols-4">@foreach(range(0, 3) as $slot)<label class="museum-field"><span>Artist Box {{ $slot + 1 }}</span><select name="featured_artist_ids[]"><option value="">Coming Soon</option>@foreach($artists as $profile)<option value="{{ $profile->id }}" @selected((string) old('featured_artist_ids.'.$slot, $selectedArtistIds[$slot] ?? '') === (string) $profile->id)>{{ $profile->artist?->name ?: 'Unknown artist' }}</option>@endforeach</select></label>@endforeach</div></div>
    <div><h3 class="font-semibold">Selected Works — 3 fixed boxes</h3><p class="text-sm text-zinc-500">Choose the artwork displayed in each position.</p><div class="mt-3 grid gap-4 md:grid-cols-3">@foreach(range(0, 2) as $slot)<label class="museum-field"><span>Artwork Box {{ $slot + 1 }}</span><select name="selected_work_ids[]"><option value="">Coming Soon</option>@foreach($works as $item)<option value="{{ $item->id }}" @selected((string) old('selected_work_ids.'.$slot, $selectedWorkIds[$slot] ?? '') === (string) $item->id)>{{ $item->artwork?->title ?: 'Untitled' }} — {{ $item->artwork?->artist?->name ?: 'Unknown artist' }}</option>@endforeach</select></label>@endforeach</div></div>
</div></details>
<details class="museum-panel" open><summary class="museum-section-title cursor-pointer">Experience</summary><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="museum-field"><span>Title *</span><input name="public_home_experience_title" value="{{ old('public_home_experience_title', $content['public_home_experience_title']) }}" required></label><label class="museum-field"><span>Button Text *</span><input name="public_home_experience_button" value="{{ old('public_home_experience_button', $content['public_home_experience_button']) }}" required></label><label class="museum-field md:col-span-2"><span>Description *</span><textarea name="public_home_experience_description" rows="3" required>{{ old('public_home_experience_description', $content['public_home_experience_description']) }}</textarea></label></div></details>
<details class="museum-panel" open><summary class="museum-section-title cursor-pointer">Vision</summary><div class="mt-5 grid gap-4 md:grid-cols-2"><label class="museum-field"><span>Title *</span><input name="public_home_vision_title" value="{{ old('public_home_vision_title', $content['public_home_vision_title']) }}" required></label><label class="museum-field"><span>Button Text *</span><input name="public_home_vision_button" value="{{ old('public_home_vision_button', $content['public_home_vision_button']) }}" required></label><label class="museum-field md:col-span-2"><span>Paragraph 1 *</span><textarea name="public_home_vision_paragraph_1" rows="3" required>{{ old('public_home_vision_paragraph_1', $content['public_home_vision_paragraph_1']) }}</textarea></label><label class="museum-field md:col-span-2"><span>Paragraph 2 *</span><textarea name="public_home_vision_paragraph_2" rows="3" required>{{ old('public_home_vision_paragraph_2', $content['public_home_vision_paragraph_2']) }}</textarea></label><label class="museum-field md:col-span-2"><span>Highlighted Note *</span><textarea name="public_home_vision_note" rows="2" required>{{ old('public_home_vision_note', $content['public_home_vision_note']) }}</textarea></label></div></details>
<div class="sticky bottom-4 z-20 flex justify-end"><button class="museum-btn shadow-lg" type="submit">Save Home Page</button></div></form></section>
</x-layout>
